name: BasicImages

on:
  workflow_dispatch:

  schedule:
    - cron: "0 23 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./configs/basic/auth.yaml
          images_file: ./configs/basic/images.yaml
          version: latest
          proc: 10
          arch: amd64
        env:
          DEST_REGISTRY: ${{ secrets.DEST_REGISTRY }}
          DEST_USERNAME: ${{ secrets.DEST_USERNAME }}
          DEST_PASSWORD: ${{ secrets.DEST_PASSWORD }}
